// Generated by psc-bundle 0.10.7
var PS = {};
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });
  var compose = function (dict) {
      return dict.compose;
  };
  exports["Semigroupoid"] = Semigroupoid;
  exports["compose"] = compose;
  exports["semigroupoidFn"] = semigroupoidFn;
})(PS["Control.Semigroupoid"] = PS["Control.Semigroupoid"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var Control_Semigroupoid = PS["Control.Semigroupoid"];        
  var Category = function (__superclass_Control$dotSemigroupoid$dotSemigroupoid_0, id) {
      this["__superclass_Control.Semigroupoid.Semigroupoid_0"] = __superclass_Control$dotSemigroupoid$dotSemigroupoid_0;
      this.id = id;
  };
  var id = function (dict) {
      return dict.id;
  };
  var categoryFn = new Category(function () {
      return Control_Semigroupoid.semigroupoidFn;
  }, function (x) {
      return x;
  });
  exports["Category"] = Category;
  exports["id"] = id;
  exports["categoryFn"] = categoryFn;
})(PS["Control.Category"] = PS["Control.Category"] || {});
(function(exports) {
    "use strict";

  exports.replicate = function (count) {
    return function (value) {
      var result = [];
      var n = 0;
      for (var i = 0; i < count; i++) {
        result[n++] = value;
      }
      return result;
    };
  };   

  //------------------------------------------------------------------------------
  // Array size ------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.length = function (xs) {
    return xs.length;
  };

  exports.snoc = function (l) {
    return function (e) {
      var l1 = l.slice();
      l1.push(e);
      return l1;
    };
  };

  //------------------------------------------------------------------------------
  // Indexed operations ----------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.indexImpl = function (just) {
    return function (nothing) {
      return function (xs) {
        return function (i) {
          return i < 0 || i >= xs.length ? nothing :  just(xs[i]);
        };
      };
    };
  };

  exports._deleteAt = function (just) {
    return function (nothing) {
      return function (i) {
        return function (l) {
          if (i < 0 || i >= l.length) return nothing;
          var l1 = l.slice();
          l1.splice(i, 1);
          return just(l1);
        };
      };
    };
  };

  exports._updateAt = function (just) {
    return function (nothing) {
      return function (i) {
        return function (a) {
          return function (l) {
            if (i < 0 || i >= l.length) return nothing;
            var l1 = l.slice();
            l1[i] = a;
            return just(l1);
          };
        };
      };
    };
  };

  //------------------------------------------------------------------------------
  // Subarrays -------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.slice = function (s) {
    return function (e) {
      return function (l) {
        return l.slice(s, e);
      };
    };
  };
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var $foreign = PS["Data.Eq"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Void = PS["Data.Void"];        
  var Eq = function (eq) {
      this.eq = eq;
  };
  var eq = function (dict) {
      return dict.eq;
  };
  exports["Eq"] = Eq;
  exports["eq"] = eq;
})(PS["Data.Eq"] = PS["Data.Eq"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var $foreign = PS["Data.Show"];     
  var Show = function (show) {
      this.show = show;
  }; 
  var show = function (dict) {
      return dict.show;
  };
  exports["Show"] = Show;
  exports["show"] = show;
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadZero = PS["Control.MonadZero"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Functor = PS["Data.Functor"];
  var Control_Apply = PS["Control.Apply"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad = PS["Control.Monad"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Bounded = PS["Data.Bounded"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  var Data_Function = PS["Data.Function"];
  var Control_Category = PS["Control.Category"];        
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (v) {
      return function (v1) {
          return function (v2) {
              if (v2 instanceof Nothing) {
                  return v;
              };
              if (v2 instanceof Just) {
                  return v1(v2.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe line 220, column 1 - line 220, column 22: " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
          };
      };
  };
  var fromMaybe = function (a) {
      return maybe(a)(Control_Category.id(Control_Category.categoryFn));
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["fromMaybe"] = fromMaybe;
  exports["maybe"] = maybe;
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var $foreign = PS["Data.Array"];
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad_Rec_Class = PS["Control.Monad.Rec.Class"];
  var Control_Monad_ST = PS["Control.Monad.ST"];
  var Data_Array_ST = PS["Data.Array.ST"];
  var Data_Array_ST_Iterator = PS["Data.Array.ST.Iterator"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_NonEmpty = PS["Data.NonEmpty"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Data_Function = PS["Data.Function"];
  var Data_Ord = PS["Data.Ord"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Boolean = PS["Data.Boolean"];
  var Data_Ordering = PS["Data.Ordering"];
  var Data_Ring = PS["Data.Ring"];
  var Data_Eq = PS["Data.Eq"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Control_Apply = PS["Control.Apply"];
  var Data_Functor = PS["Data.Functor"];
  var Control_Applicative = PS["Control.Applicative"];
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Semigroupoid = PS["Control.Semigroupoid"];
  var Data_Semigroup = PS["Data.Semigroup"];
  var Control_Category = PS["Control.Category"];      
  var updateAt = $foreign._updateAt(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var index = $foreign.indexImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var deleteAt = $foreign._deleteAt(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  exports["deleteAt"] = deleteAt;
  exports["index"] = index;
  exports["updateAt"] = updateAt;
  exports["replicate"] = $foreign.replicate;
  exports["snoc"] = $foreign.snoc;
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function(exports) {
  // Generated by psc version 0.10.7
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Array = PS["Data.Array"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Show = PS["Data.Show"];
  var Data_Eq = PS["Data.Eq"];
  var Data_Function = PS["Data.Function"];
  var Data_Semiring = PS["Data.Semiring"];
  var Data_Ring = PS["Data.Ring"];
  var Data_HeytingAlgebra = PS["Data.HeytingAlgebra"];
  var Data_Semigroup = PS["Data.Semigroup"];        
  var Axe = (function () {
      function Axe() {

      };
      Axe.value = new Axe();
      return Axe;
  })();
  var Dagger = (function () {
      function Dagger() {

      };
      Dagger.value = new Dagger();
      return Dagger;
  })();
  var Sword = (function () {
      function Sword() {

      };
      Sword.value = new Sword();
      return Sword;
  })();
  var Common = (function () {
      function Common() {

      };
      Common.value = new Common();
      return Common;
  })();
  var Rusty = (function () {
      function Rusty() {

      };
      Rusty.value = new Rusty();
      return Rusty;
  })();
  var Masterwork = (function () {
      function Masterwork() {

      };
      Masterwork.value = new Masterwork();
      return Masterwork;
  })();
  var Mine = (function () {
      function Mine() {

      };
      Mine.value = new Mine();
      return Mine;
  })();
  var GoblinCave = (function () {
      function GoblinCave() {

      };
      GoblinCave.value = new GoblinCave();
      return GoblinCave;
  })();
  var Cave = (function () {
      function Cave() {

      };
      Cave.value = new Cave();
      return Cave;
  })();
  var WizardTower = (function () {
      function WizardTower() {

      };
      WizardTower.value = new WizardTower();
      return WizardTower;
  })();
  var Ground = (function () {
      function Ground(value0) {
          this.value0 = value0;
      };
      Ground.create = function (value0) {
          return new Ground(value0);
      };
      return Ground;
  })();
  var Wall = (function () {
      function Wall(value0) {
          this.value0 = value0;
      };
      Wall.create = function (value0) {
          return new Wall(value0);
      };
      return Wall;
  })();
  var Mountain = (function () {
      function Mountain(value0) {
          this.value0 = value0;
      };
      Mountain.create = function (value0) {
          return new Mountain(value0);
      };
      return Mountain;
  })();
  var Forest = (function () {
      function Forest(value0) {
          this.value0 = value0;
      };
      Forest.create = function (value0) {
          return new Forest(value0);
      };
      return Forest;
  })();
  var Water = (function () {
      function Water(value0) {
          this.value0 = value0;
      };
      Water.create = function (value0) {
          return new Water(value0);
      };
      return Water;
  })();
  var Puddle = (function () {
      function Puddle(value0) {
          this.value0 = value0;
      };
      Puddle.create = function (value0) {
          return new Puddle(value0);
      };
      return Puddle;
  })();
  var Door = (function () {
      function Door(value0) {
          this.value0 = value0;
      };
      Door.create = function (value0) {
          return new Door(value0);
      };
      return Door;
  })();
  var StairsUp = (function () {
      function StairsUp() {

      };
      StairsUp.value = new StairsUp();
      return StairsUp;
  })();
  var StairsDown = (function () {
      function StairsDown() {

      };
      StairsDown.value = new StairsDown();
      return StairsDown;
  })();
  var DungeonEntrance = (function () {
      function DungeonEntrance() {

      };
      DungeonEntrance.value = new DungeonEntrance();
      return DungeonEntrance;
  })();
  var ErrorTile = (function () {
      function ErrorTile() {

      };
      ErrorTile.value = new ErrorTile();
      return ErrorTile;
  })();
  var Player = (function () {
      function Player(value0) {
          this.value0 = value0;
      };
      Player.create = function (value0) {
          return new Player(value0);
      };
      return Player;
  })();
  var AlphaWolf = (function () {
      function AlphaWolf() {

      };
      AlphaWolf.value = new AlphaWolf();
      return AlphaWolf;
  })();
  var Wolf = (function () {
      function Wolf() {

      };
      Wolf.value = new Wolf();
      return Wolf;
  })();
  var Goblin = (function () {
      function Goblin() {

      };
      Goblin.value = new Goblin();
      return Goblin;
  })();
  var Snowman = (function () {
      function Snowman() {

      };
      Snowman.value = new Snowman();
      return Snowman;
  })();
  var Tim = (function () {
      function Tim() {

      };
      Tim.value = new Tim();
      return Tim;
  })();
  var Ismo = (function () {
      function Ismo() {

      };
      Ismo.value = new Ismo();
      return Ismo;
  })();
  var Cloak = (function () {
      function Cloak() {

      };
      Cloak.value = new Cloak();
      return Cloak;
  })();
  var Chest = (function () {
      function Chest() {

      };
      Chest.value = new Chest();
      return Chest;
  })();
  var Gloves = (function () {
      function Gloves() {

      };
      Gloves.value = new Gloves();
      return Gloves;
  })();
  var CommonA = (function () {
      function CommonA() {

      };
      CommonA.value = new CommonA();
      return CommonA;
  })();
  var LightA = (function () {
      function LightA() {

      };
      LightA.value = new LightA();
      return LightA;
  })();
  var ThickA = (function () {
      function ThickA() {

      };
      ThickA.value = new ThickA();
      return ThickA;
  })();
  var MasterworkA = (function () {
      function MasterworkA() {

      };
      MasterworkA.value = new MasterworkA();
      return MasterworkA;
  })();
  var Weapon = (function () {
      function Weapon(value0) {
          this.value0 = value0;
      };
      Weapon.create = function (value0) {
          return new Weapon(value0);
      };
      return Weapon;
  })();
  var Armour = (function () {
      function Armour(value0) {
          this.value0 = value0;
      };
      Armour.create = function (value0) {
          return new Armour(value0);
      };
      return Armour;
  })();
  var Wood = (function () {
      function Wood() {

      };
      Wood.value = new Wood();
      return Wood;
  })();
  var ErrorItem = (function () {
      function ErrorItem() {

      };
      ErrorItem.value = new ErrorItem();
      return ErrorItem;
  })();
  var Creature = function (x) {
      return x;
  };
  var GameState = function (x) {
      return x;
  };
  var weaponWeight = function (v) {
      if (v instanceof Dagger) {
          return 4;
      };
      if (v instanceof Axe) {
          return 12;
      };
      return 10;
  };
  var weaponPrefixWeight = function (v) {
      if (v instanceof Rusty) {
          return 8;
      };
      if (v instanceof Masterwork) {
          return 9;
      };
      return 10;
  };
  var tileIcon = function (v) {
      if (v instanceof Ground) {
          return ".";
      };
      if (v instanceof Wall) {
          return "#";
      };
      if (v instanceof Mountain) {
          return "^";
      };
      if (v instanceof Forest) {
          return "T";
      };
      if (v instanceof Water) {
          return "~";
      };
      if (v instanceof Puddle) {
          if (v.value0.frozen) {
              return "#";
          };
          if (!v.value0.frozen) {
              return ".";
          };
          throw new Error("Failed pattern match at Rogue line 132, column 30 - line 133, column 1: " + [ v.value0.frozen.constructor.name ]);
      };
      if (v instanceof Door) {
          return "+";
      };
      if (v instanceof StairsUp) {
          return "<";
      };
      if (v instanceof StairsDown) {
          return ">";
      };
      if (v instanceof DungeonEntrance) {
          return "o";
      };
      return "?";
  };
  var showTile = new Data_Show.Show(function (v) {
      if (v instanceof Ground) {
          return "Ground";
      };
      if (v instanceof Wall) {
          return "Wall";
      };
      if (v instanceof Mountain) {
          return "Mountain";
      };
      if (v instanceof Forest) {
          return "Forest";
      };
      if (v instanceof Water) {
          return "Water";
      };
      if (v instanceof Puddle) {
          return "Puddle";
      };
      if (v instanceof Door) {
          return "Door";
      };
      if (v instanceof StairsUp) {
          return "StairsUp";
      };
      if (v instanceof StairsDown) {
          return "StairsDown";
      };
      if (v instanceof DungeonEntrance) {
          return "DungeonEntrance";
      };
      if (v instanceof ErrorTile) {
          return "ErrorTile";
      };
      throw new Error("Failed pattern match at Rogue line 99, column 5 - line 100, column 5: " + [ v.constructor.name ]);
  });
  var showCreature = new Data_Show.Show(function (v) {
      if (v.creatureType instanceof Player) {
          return v.creatureType.value0.name;
      };
      if (v.creatureType instanceof AlphaWolf) {
          return "alpha wolf";
      };
      if (v.creatureType instanceof Wolf) {
          return "wolf";
      };
      if (v.creatureType instanceof Goblin) {
          return "goblin";
      };
      if (v.creatureType instanceof Snowman) {
          return "snowman";
      };
      if (v.creatureType instanceof Tim) {
          return "evil sorcerer";
      };
      return "Ismo";
  });
  var setPlayer = function (v) {
      return function (pl) {
          var $86 = {};
          for (var $87 in v) {
              if ({}.hasOwnProperty.call(v, $87)) {
                  $86[$87] = v[$87];
              };
          };
          $86.player = pl;
          return $86;
      };
  };
  var setLevelTile = function (level) {
      return function (t) {
          return function (p) {
              var $89 = {};
              for (var $90 in level) {
                  if ({}.hasOwnProperty.call(level, $90)) {
                      $89[$90] = level[$90];
                  };
              };
              $89.tiles = Data_Maybe.fromMaybe(level.tiles)(Data_Array.updateAt((p.y * level.width | 0) + p.x | 0)(t)(level.tiles));
              return $89;
          };
      };
  };
  var setTile = function (v) {
      return function (t) {
          return function (p) {
              var $95 = {};
              for (var $96 in v) {
                  if ({}.hasOwnProperty.call(v, $96)) {
                      $95[$96] = v[$96];
                  };
              };
              $95.level = setLevelTile(v.level)(t)(p);
              return $95;
          };
      };
  };
  var randomItem = function (v) {
      return function (v1) {
          return Wood.value;
      };
  };
  var randomCreature = function (v) {
      return function (v1) {
          return function (p) {
              return {
                  creatureType: Ismo.value, 
                  pos: p, 
                  stats: {
                      hpMax: 50, 
                      hp: 50, 
                      str: 9, 
                      dex: 12, 
                      "int": 6
                  }, 
                  inv: [  ]
              };
          };
      };
  };
  var pointPlus = function (v) {
      return function (v1) {
          return {
              x: v.x + v1.x | 0, 
              y: v.y + v1.y | 0
          };
      };
  };
  var pointMinus = function (v) {
      return function (v1) {
          return {
              x: v.x - v1.x | 0, 
              y: v.y - v1.y | 0
          };
      };
  };
  var pointEquals = function (v) {
      return function (v1) {
          return v.x === v1.x && v.y === v1.y;
      };
  };
  var isTileTransparent = function (v) {
      if (v instanceof Wall) {
          return false;
      };
      if (v instanceof Mountain) {
          return false;
      };
      return true;
  };
  var isTileSolid = function (v) {
      if (v instanceof Ground) {
          return false;
      };
      if (v instanceof Forest) {
          return false;
      };
      if (v instanceof Water) {
          return !v.value0.frozen;
      };
      if (v instanceof Puddle) {
          return v.value0.frozen;
      };
      if (v instanceof DungeonEntrance) {
          return false;
      };
      if (v instanceof StairsUp) {
          return false;
      };
      if (v instanceof StairsDown) {
          return false;
      };
      return true;
  };
  var isCorrectArmour = function (v) {
      return function (v1) {
          return function (v2) {
              if (v1 instanceof Cloak && v2 === 1) {
                  return new Data_Maybe.Just(v);
              };
              if (v1 instanceof Chest && v2 === 2) {
                  return new Data_Maybe.Just(v);
              };
              if (v1 instanceof Gloves && v2 === 3) {
                  return new Data_Maybe.Just(v);
              };
              return Data_Maybe.Nothing.value;
          };
      };
  };
  var getPlayer = function (v) {
      return v.player;
  };
  var getLevelTile = function (level) {
      return function (p) {
          return Data_Maybe.fromMaybe(ErrorTile.value)(Data_Array.index(level.tiles)((p.y * level.width | 0) + p.x | 0));
      };
  };
  var getTile = function (v) {
      return function (p) {
          return getLevelTile(v.level)(p);
      };
  };
  var frozenColor = function (v) {
      if (v.frozen) {
          return "0.2)";
      };
      if (!v.frozen) {
          return "0.6)";
      };
      throw new Error("Failed pattern match at Rogue line 140, column 1 - line 141, column 1: " + [ v.constructor.name ]);
  };
  var tileColor = function (v) {
      if (v instanceof Ground) {
          return "rgba(139, 69, 19, " + frozenColor(v.value0);
      };
      if (v instanceof Wall) {
          return "rgba(120, 120, 120, " + frozenColor(v.value0);
      };
      if (v instanceof Mountain) {
          return "rgba(70, 70, 70, " + frozenColor(v.value0);
      };
      if (v instanceof Forest) {
          return "rgba(20, 240, 30, " + frozenColor(v.value0);
      };
      if (v instanceof Water) {
          return "rgba(20, 20, 250, " + frozenColor(v.value0);
      };
      if (v instanceof Puddle) {
          return "rgba(20, 20, 250, " + frozenColor(v.value0);
      };
      if (v instanceof Door) {
          return "rgba(200, 180, 50, " + frozenColor(v.value0);
      };
      return "rgba(120, 120, 120, 0.6)";
  };
  var equip = function (v) {
      return function (v1) {
          return function (v2) {
              if (v1 instanceof Armour && v2 === 1) {
                  var $147 = {};
                  for (var $148 in v) {
                      if ({}.hasOwnProperty.call(v, $148)) {
                          $147[$148] = v[$148];
                      };
                  };
                  $147.equipment = (function () {
                      var $144 = {};
                      for (var $145 in v.equipment) {
                          if ({}.hasOwnProperty.call(v.equipment, $145)) {
                              $144[$145] = v["equipment"][$145];
                          };
                      };
                      $144.cloak = isCorrectArmour(new Armour(v1.value0))(v1.value0.armourType)(1);
                      return $144;
                  })();
                  return $147;
              };
              if (v1 instanceof Armour && v2 === 2) {
                  var $154 = {};
                  for (var $155 in v) {
                      if ({}.hasOwnProperty.call(v, $155)) {
                          $154[$155] = v[$155];
                      };
                  };
                  $154.equipment = (function () {
                      var $151 = {};
                      for (var $152 in v.equipment) {
                          if ({}.hasOwnProperty.call(v.equipment, $152)) {
                              $151[$152] = v["equipment"][$152];
                          };
                      };
                      $151.chest = isCorrectArmour(new Armour(v1.value0))(v1.value0.armourType)(2);
                      return $151;
                  })();
                  return $154;
              };
              if (v1 instanceof Armour && v2 === 3) {
                  var $161 = {};
                  for (var $162 in v) {
                      if ({}.hasOwnProperty.call(v, $162)) {
                          $161[$162] = v[$162];
                      };
                  };
                  $161.equipment = (function () {
                      var $158 = {};
                      for (var $159 in v.equipment) {
                          if ({}.hasOwnProperty.call(v.equipment, $159)) {
                              $158[$159] = v["equipment"][$159];
                          };
                      };
                      $158.hands = isCorrectArmour(new Armour(v1.value0))(v1.value0.armourType)(3);
                      return $158;
                  })();
                  return $161;
              };
              if (v2 === 4) {
                  var $168 = {};
                  for (var $169 in v) {
                      if ({}.hasOwnProperty.call(v, $169)) {
                          $168[$169] = v[$169];
                      };
                  };
                  $168.equipment = (function () {
                      var $165 = {};
                      for (var $166 in v.equipment) {
                          if ({}.hasOwnProperty.call(v.equipment, $166)) {
                              $165[$166] = v["equipment"][$166];
                          };
                      };
                      $165.weapon = new Data_Maybe.Just(v1);
                      return $165;
                  })();
                  return $168;
              };
              return v;
          };
      };
  };
  var eqTheme = new Data_Eq.Eq(function (v) {
      return function (v1) {
          if (v instanceof Mine && v1 instanceof Mine) {
              return true;
          };
          if (v instanceof GoblinCave && v1 instanceof GoblinCave) {
              return true;
          };
          if (v instanceof Cave && v1 instanceof Cave) {
              return true;
          };
          if (v instanceof WizardTower && v1 instanceof WizardTower) {
              return true;
          };
          return false;
      };
  });
  var deleteItem = function (v) {
      return function (i) {
          var $175 = {};
          for (var $176 in v) {
              if ({}.hasOwnProperty.call(v, $176)) {
                  $175[$176] = v[$176];
              };
          };
          $175.inv = Data_Maybe.fromMaybe(v.inv)(Data_Array.deleteAt(i)(v.inv));
          return $175;
      };
  };
  var defaultStats = {
      hpMax: 200, 
      hp: 200, 
      str: 10, 
      dex: 10, 
      "int": 10
  };
  var creatureBaseDmg = function (v) {
      if (v.creatureType instanceof AlphaWolf) {
          return 2;
      };
      if (v.creatureType instanceof Snowman) {
          return 4;
      };
      if (v.creatureType instanceof Tim) {
          return 10;
      };
      return 1;
  };
  var dmg = function (v) {
      return v.stats.str * creatureBaseDmg(v) | 0;
  };
  var createLevel = function (x) {
      return function (y) {
          return function (t) {
              var zero = {
                  x: 0, 
                  y: 0
              };
              return {
                  tiles: Data_Array.replicate(x * y | 0)(t), 
                  width: x, 
                  height: y, 
                  enemies: [  ], 
                  items: [  ], 
                  up: zero, 
                  down: zero
              };
          };
      };
  };
  var initialGameState = {
      level: createLevel(75)(25)(new Ground({
          frozen: false
      })), 
      player: {
          creatureType: new Player({
              name: "Frozty"
          }), 
          pos: {
              x: 10, 
              y: 10
          }, 
          stats: defaultStats, 
          inv: [  ]
      }, 
      coldStatus: 100, 
      equipment: {
          cloak: Data_Maybe.Nothing.value, 
          chest: Data_Maybe.Nothing.value, 
          hands: Data_Maybe.Nothing.value, 
          weapon: Data_Maybe.Nothing.value
      }
  };
  var attack = function (v) {
      return function (v1) {
          var $188 = {};
          for (var $189 in v1) {
              if ({}.hasOwnProperty.call(v1, $189)) {
                  $188[$189] = v1[$189];
              };
          };
          $188.stats = (function () {
              var $185 = {};
              for (var $186 in v1.stats) {
                  if ({}.hasOwnProperty.call(v1.stats, $186)) {
                      $185[$186] = v1["stats"][$186];
                  };
              };
              $185.hp = v1.stats.hp - dmg(v) | 0;
              return $185;
          })();
          return $188;
      };
  };
  var armourWeight = function (v) {
      if (v instanceof Chest) {
          return 20;
      };
      if (v instanceof Gloves) {
          return 2;
      };
      return 10;
  };
  var armourPrefixWeight = function (v) {
      if (v instanceof LightA) {
          return 5;
      };
      if (v instanceof ThickA) {
          return 13;
      };
      if (v instanceof MasterworkA) {
          return 8;
      };
      return 10;
  };
  var itemWeight = function (v) {
      if (v instanceof Weapon) {
          return weaponWeight(v.value0.weaponType) + weaponPrefixWeight(v.value0.prefixe) | 0;
      };
      if (v instanceof Armour) {
          return armourWeight(v.value0.armourType) + armourPrefixWeight(v.value0.prefixe) | 0;
      };
      if (v instanceof Wood) {
          return 10;
      };
      return 2;
  };
  var addItem = function (v) {
      return function (v1) {
          if (v1 instanceof Data_Maybe.Just) {
              var $198 = {};
              for (var $199 in v) {
                  if ({}.hasOwnProperty.call(v, $199)) {
                      $198[$199] = v[$199];
                  };
              };
              $198.inv = Data_Array.snoc(v.inv)(v1.value0);
              return $198;
          };
          return v;
      };
  };
  var unEquip = function (v) {
      return function (v1) {
          if (v1 === 1) {
              var $207 = {};
              for (var $208 in v) {
                  if ({}.hasOwnProperty.call(v, $208)) {
                      $207[$208] = v[$208];
                  };
              };
              $207.equipment = (function () {
                  var $204 = {};
                  for (var $205 in v.equipment) {
                      if ({}.hasOwnProperty.call(v.equipment, $205)) {
                          $204[$205] = v["equipment"][$205];
                      };
                  };
                  $204.cloak = Data_Maybe.Nothing.value;
                  return $204;
              })();
              $207.player = addItem(v.player)(v.equipment.cloak);
              return $207;
          };
          if (v1 === 2) {
              var $213 = {};
              for (var $214 in v) {
                  if ({}.hasOwnProperty.call(v, $214)) {
                      $213[$214] = v[$214];
                  };
              };
              $213.equipment = (function () {
                  var $210 = {};
                  for (var $211 in v.equipment) {
                      if ({}.hasOwnProperty.call(v.equipment, $211)) {
                          $210[$211] = v["equipment"][$211];
                      };
                  };
                  $210.chest = Data_Maybe.Nothing.value;
                  return $210;
              })();
              $213.player = addItem(v.player)(v.equipment.chest);
              return $213;
          };
          if (v1 === 3) {
              var $219 = {};
              for (var $220 in v) {
                  if ({}.hasOwnProperty.call(v, $220)) {
                      $219[$220] = v[$220];
                  };
              };
              $219.equipment = (function () {
                  var $216 = {};
                  for (var $217 in v.equipment) {
                      if ({}.hasOwnProperty.call(v.equipment, $217)) {
                          $216[$217] = v["equipment"][$217];
                      };
                  };
                  $216.hands = Data_Maybe.Nothing.value;
                  return $216;
              })();
              $219.player = addItem(v.player)(v.equipment.hands);
              return $219;
          };
          if (v1 === 4) {
              var $225 = {};
              for (var $226 in v) {
                  if ({}.hasOwnProperty.call(v, $226)) {
                      $225[$226] = v[$226];
                  };
              };
              $225.equipment = (function () {
                  var $222 = {};
                  for (var $223 in v.equipment) {
                      if ({}.hasOwnProperty.call(v.equipment, $223)) {
                          $222[$223] = v["equipment"][$223];
                      };
                  };
                  $222.weapon = Data_Maybe.Nothing.value;
                  return $222;
              })();
              $225.player = addItem(v.player)(v.equipment.weapon);
              return $225;
          };
          return v;
      };
  };
  exports["CommonA"] = CommonA;
  exports["LightA"] = LightA;
  exports["ThickA"] = ThickA;
  exports["MasterworkA"] = MasterworkA;
  exports["Cloak"] = Cloak;
  exports["Chest"] = Chest;
  exports["Gloves"] = Gloves;
  exports["Creature"] = Creature;
  exports["Player"] = Player;
  exports["AlphaWolf"] = AlphaWolf;
  exports["Wolf"] = Wolf;
  exports["Goblin"] = Goblin;
  exports["Snowman"] = Snowman;
  exports["Tim"] = Tim;
  exports["Ismo"] = Ismo;
  exports["GameState"] = GameState;
  exports["Weapon"] = Weapon;
  exports["Armour"] = Armour;
  exports["Wood"] = Wood;
  exports["ErrorItem"] = ErrorItem;
  exports["Mine"] = Mine;
  exports["GoblinCave"] = GoblinCave;
  exports["Cave"] = Cave;
  exports["WizardTower"] = WizardTower;
  exports["Ground"] = Ground;
  exports["Wall"] = Wall;
  exports["Mountain"] = Mountain;
  exports["Forest"] = Forest;
  exports["Water"] = Water;
  exports["Puddle"] = Puddle;
  exports["Door"] = Door;
  exports["StairsUp"] = StairsUp;
  exports["StairsDown"] = StairsDown;
  exports["DungeonEntrance"] = DungeonEntrance;
  exports["ErrorTile"] = ErrorTile;
  exports["Common"] = Common;
  exports["Rusty"] = Rusty;
  exports["Masterwork"] = Masterwork;
  exports["Axe"] = Axe;
  exports["Dagger"] = Dagger;
  exports["Sword"] = Sword;
  exports["addItem"] = addItem;
  exports["armourPrefixWeight"] = armourPrefixWeight;
  exports["armourWeight"] = armourWeight;
  exports["attack"] = attack;
  exports["createLevel"] = createLevel;
  exports["creatureBaseDmg"] = creatureBaseDmg;
  exports["defaultStats"] = defaultStats;
  exports["deleteItem"] = deleteItem;
  exports["dmg"] = dmg;
  exports["equip"] = equip;
  exports["frozenColor"] = frozenColor;
  exports["getLevelTile"] = getLevelTile;
  exports["getPlayer"] = getPlayer;
  exports["getTile"] = getTile;
  exports["initialGameState"] = initialGameState;
  exports["isCorrectArmour"] = isCorrectArmour;
  exports["isTileSolid"] = isTileSolid;
  exports["isTileTransparent"] = isTileTransparent;
  exports["itemWeight"] = itemWeight;
  exports["pointEquals"] = pointEquals;
  exports["pointMinus"] = pointMinus;
  exports["pointPlus"] = pointPlus;
  exports["randomCreature"] = randomCreature;
  exports["randomItem"] = randomItem;
  exports["setLevelTile"] = setLevelTile;
  exports["setPlayer"] = setPlayer;
  exports["setTile"] = setTile;
  exports["tileColor"] = tileColor;
  exports["tileIcon"] = tileIcon;
  exports["unEquip"] = unEquip;
  exports["weaponPrefixWeight"] = weaponPrefixWeight;
  exports["weaponWeight"] = weaponWeight;
  exports["showCreature"] = showCreature;
  exports["showTile"] = showTile;
  exports["eqTheme"] = eqTheme;
})(PS["Rogue"] = PS["Rogue"] || {});
